// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katz.test.pizza.domain;

import com.katz.test.pizza.domain.PizzaOrderPk;
import java.io.Serializable;

privileged aspect PizzaOrderPk_Roo_Serializable {
    
    declare parents: PizzaOrderPk implements Serializable;
    
    private static final long PizzaOrderPk.serialVersionUID = 1L;
    
}
