// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katz.test.pizza.domain;

import com.katz.test.pizza.domain.Topping;

privileged aspect Topping_Roo_JavaBean {
    
    public String Topping.getName() {
        return this.name;
    }
    
    public void Topping.setName(String name) {
        this.name = name;
    }
    
}
