// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katz.test.pizza.domain;

import com.katz.test.pizza.domain.PizzaOrderDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PizzaOrderDataOnDemand_Roo_Configurable {
    
    declare @type: PizzaOrderDataOnDemand: @Configurable;
    
}
