// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katz.test.pizza.repository;

import com.katz.test.pizza.domain.Base;
import com.katz.test.pizza.repository.BaseRepository;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

privileged aspect BaseRepository_Roo_Jpa_Repository {
    
    declare parents: BaseRepository extends JpaRepository<Base, Long>;
    
    declare parents: BaseRepository extends JpaSpecificationExecutor<Base>;
    
    declare @type: BaseRepository: @Repository;
    
}
