// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katz.test.pizza.repository;

import com.katz.test.pizza.domain.Pizza;
import com.katz.test.pizza.repository.PizzaRepository;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

privileged aspect PizzaRepository_Roo_Jpa_Repository {
    
    declare parents: PizzaRepository extends JpaRepository<Pizza, Long>;
    
    declare parents: PizzaRepository extends JpaSpecificationExecutor<Pizza>;
    
    declare @type: PizzaRepository: @Repository;
    
}
