// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katz.test.pizza.service;

import com.katz.test.pizza.domain.Pizza;
import com.katz.test.pizza.service.PizzaService;
import java.util.List;

privileged aspect PizzaService_Roo_Service {
    
    public abstract long PizzaService.countAllPizzas();    
    public abstract void PizzaService.deletePizza(Pizza pizza);    
    public abstract Pizza PizzaService.findPizza(Long id);    
    public abstract List<Pizza> PizzaService.findAllPizzas();    
    public abstract List<Pizza> PizzaService.findPizzaEntries(int firstResult, int maxResults);    
    public abstract void PizzaService.savePizza(Pizza pizza);    
    public abstract Pizza PizzaService.updatePizza(Pizza pizza);    
}
