// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katz.test.pizza.service;

import com.katz.test.pizza.domain.Topping;
import com.katz.test.pizza.service.ToppingService;
import java.util.List;

privileged aspect ToppingService_Roo_Service {
    
    public abstract long ToppingService.countAllToppings();    
    public abstract void ToppingService.deleteTopping(Topping topping);    
    public abstract Topping ToppingService.findTopping(Long id);    
    public abstract List<Topping> ToppingService.findAllToppings();    
    public abstract List<Topping> ToppingService.findToppingEntries(int firstResult, int maxResults);    
    public abstract void ToppingService.saveTopping(Topping topping);    
    public abstract Topping ToppingService.updateTopping(Topping topping);    
}
